Stop building with OpenSSL 1.1.
conda-forge/azure-core-cpp-feedstock pull request #16
Opened 2024-02-26 19:39 UTC by teo-tsirpanis

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

2024-02-26 19:39 UTC, teo-tsirpanis commented
@conda-forge-admin, please rerender

2024-02-26 19:58 UTC, jdblischak requested changes

2024-02-26 19:58 UTC, jdblischak commented on recipe/meta.yaml
> +  number: 1
I don't think there is any need to upload new binaries for this change. We are simply dropping build variants. Bumping the build number to 1 will cause an identical libcurl8/openssl3 variant to be uploaded to anaconda.org

2024-02-26 22:01 UTC, teo-tsirpanis commented on recipe/meta.yaml
> +  number: 1
Reverted.

2024-02-26 22:26 UTC, jjerphan requested changes
I just have one comment.

2024-02-26 22:26 UTC, jjerphan commented on recipe/conda_build_config.yaml
> -- 7
I think the title of the PR must be changed to include the removal of libcurl 7.

2024-02-27 00:36 UTC, teo-tsirpanis commented on recipe/conda_build_config.yaml
> -- 7
Updated title.

2024-02-27 05:19 UTC, jjerphan approved these changes

2024-02-27 15:15 UTC, jdblischak approved these changes

2024-02-27 15:54 UTC, merged